In [2]:
import numpy as np # library to handle data in a vectorized manner

import pandas as pd # library for data analsysis
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

import json # library to handle JSON files

!conda install -c conda-forge geopy --yes # uncomment this line if you haven't completed the Foursquare API lab
from geopy.geocoders import Nominatim # convert an address into latitude and longitude values

import requests # library to handle requests
from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe

# Matplotlib and associated plotting modules
import matplotlib.cm as cm
import matplotlib.colors as colors

# import k-means from clustering stage
from sklearn.cluster import KMeans

#!conda install -c conda-forge folium=0.5.0 --yes # uncomment this line if you haven't completed the Foursquare API lab
import folium # map rendering library

print('Libraries imported.')

usage: conda-script.py [-h] [-V] command ...
conda-script.py: error: unrecognized arguments: # uncomment this line if you haven't completed the Foursquare API lab


Libraries imported.


In [1]:
print('*')

*


In [106]:
df = pd.read_csv('covid-19.csv')

In [107]:
address = 'India'

geolocator = Nominatim(user_agent="ny_explorer")
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print('The geograpical coordinate of India are {}, {}.'.format(latitude, longitude))

The geograpical coordinate of India are 22.3511148, 78.6677428.


In [86]:
map_india = folium.Map(location=[latitude, longitude], zoom_start=4)

# add markers to map
for lat, lng, place_name,zone in zip(df['Latitude'], df['Longitude'], df['Place Name'],df['Zone']):
    label = folium.Popup(place_name, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=2,
        popup=label,
        color=zone,
        fill=True,
        fill_color=zone,
        fill_opacity=0.7,
        parse_html=False).add_to(map_india)  
    
map_india

In [108]:
print(df['Zone'].value_counts())

red       443
orange    178
green      63
Name: Zone, dtype: int64


In [109]:
df.drop(['index'], axis = 1) 

Unnamed: 0                                         Place Name   Latitude  \
0             0                       Green Park, Delhi, New Delhi  28.549999   
1             1                     Nilgiris District, Thamil Nadu  11.416667   
2             2          Nage Layout, Kaulkhed, Akola, Maharashtra  20.673210   
3             3                          Dahigaon Ne., Maharashtra  19.511562   
4             4                      Ambedkar Nagar, Uttar Pradesh  26.407057   
5             5                  Jothi Nagar, Pollachi, Tamil Nadu  10.638598   
6             6             Janak Nagar, Saharanpur, Uttar Pradesh  29.957846   
7             7                          Vasna, Ahmedabad, Gujarat  23.003992   
8             8              Woraiyur, Tiruchirappalli, Tamil Nadu  10.830512   
9             9  Mauli Baidwan, Sahibzada Ajit Singh Nagar, Punjab  30.678722   
10           10                       Behala, Kolkata, West Bengal  22.498140   
11           11                     Ghasiara, Kolkata, West Bengal  22.441265   
12           12    Vivekananda Pally, Behala, Kolkata, West Bengal  22.589590   
13           13                                   Kadhanga, Odisha  20.228069   
14           14                   Rajouri Garden, New Delhi, Delhi  28.641529   
15           15                        Putligarh, Amritsar, Punjab  31.632898   
16           16                  Mhasrul Gaon, Nashik, Maharashtra  20.046701   
17           17                     Madhapur, Hyderabad, Telangana  17.448294   
18           18                         Jalalipatti, Uttar Pradesh  25.279940   
19           19                 Munshi Bazar, Asansol, West Bengal  23.690611   
20           20              Sant Kabir Nagar, Nashik, Maharashtra  20.006470   
21           21                       Lokgram, Kalyan, Maharashtra  19.228762   
22           22                   Cooke Town, Bengaluru, Karnataka  13.003168   
23           23                        Egmore, Chennai, Tamil Nadu  13.073226   
24           24            Maharaja Nagar, Tirunelveli, Tamil Nadu   8.707375   
25           25                   Kajoor, Chittoor, Andhra Pradesh  13.201411   
26           26           Dayanand Nagar, Gorakhpur, Uttar Pradesh  26.791519   
27           27              Loksahakar Nagar, Nashik, Maharashtra  20.015768   
28           28                   Amarjai, Fatehpur, Uttar Pradesh  25.926411   
29           29                     Malakpet, Hyderabad, Telangana  17.373093   
30           30                        Guindy, Chennai, Tamil Nadu  13.010236   
31           31             Kalindipuram, Allahabad, Uttar Pradesh  25.430883   
32           32                   Arya Nagar, Bhilai, Chhattisgarh  21.229767   
33           33                    Rajwanshi Nagar, Saharsa, Bihar  25.892298   
34           34                    Panchavati, Nashik, Maharashtra  20.007357   
35           35                     Begumpet, Hyderabad, Telangana  17.444708   
36           36                     Perungudi, Chennai, Tamil Nadu  12.965365   
37           37                          Ladakh, Jammu and Kashmir  34.209515   
38           38                                  Mahe, Maharashtra  16.640120   
39           39                         Bindapur, New Delhi, Delhi  28.610722   
40           40                    Karkardooma, Anand Vihar, Delhi  28.652946   
41           41             Rampur Garden, Bareilly, Uttar Pradesh  28.352783   
42           42                     Sudamdih, Pathardih, Jharkhand  23.671280   
43           43                   Neminagar, Damoh, Madhya Pradesh  23.820818   
44           44                       Memnagar, Ahmedabad, Gujarat  23.052553   
45           45                   Dilshad Garden, New Delhi, Delhi  28.683903   
46           46                           Eloor, Ernakulam, Kerala  10.073232   
47           47                      Nandanam, Chennai, Tamil Nadu  13.030105   
48           48                    S

In [110]:
X = df[['Latitude','Longitude']]

In [111]:
X.head()

Latitude  Longitude
0  28.549999  77.199997
1  11.416667  76.683334
2  20.673210  77.012810
3  19.511562  75.198494
4  26.407057  82.397972

In [112]:
y = df['Zone'].values

In [113]:
import itertools
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import NullFormatter
import pandas as pd
import numpy as np
import matplotlib.ticker as ticker
from sklearn import preprocessing
%matplotlib inline

In [114]:
X= preprocessing.StandardScaler().fit(X).transform(X)
X

array([[ 1.16635858, -0.22401591],
       [-1.68515499, -0.34285855],
       [-0.14458145, -0.26707259],
       ...,
       [-0.43033492, -1.22915672],
       [ 0.72452634,  0.86613282],
       [ 0.17982191,  2.36424394]])

In [115]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (547, 2) (547,)
Test set: (137, 2) (137,)


In [116]:
from sklearn.metrics import jaccard_similarity_score
from sklearn.metrics import f1_score
from sklearn.metrics import log_loss

# K Nearest Neighbor(KNN)

In [117]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
Ks = 15
mean_acc = np.zeros((Ks-1))
std_acc = np.zeros((Ks-1))
ConfustionMx = [];
for n in range(1,Ks):
    
    #Train Model and Predict  
    neigh = KNeighborsClassifier(n_neighbors = n).fit(X_train,y_train)
    yhat=neigh.predict(X_test)
    mean_acc[n-1] = metrics.accuracy_score(y_test, yhat)

    
    std_acc[n-1]=np.std(yhat==y_test)/np.sqrt(yhat.shape[0])

mean_acc

array([0.77372263, 0.74452555, 0.72262774, 0.72992701, 0.71532847,
       0.69343066, 0.67883212, 0.7080292 , 0.69343066, 0.69343066,
       0.67153285, 0.66423358, 0.65693431, 0.64963504])

In [118]:
k = 1
#Train Model and Predict  
neigh = KNeighborsClassifier(n_neighbors = k).fit(X_train,y_train)
yhat6 = neigh.predict(X_test)
v1 = f1_score(y_test, yhat6, average='weighted')
v2 = jaccard_similarity_score(y_test, yhat6)

# Decision Tree

In [119]:
from sklearn.tree import DecisionTreeClassifier

In [120]:
max_d = 3
ks = 15
mean_ax = np.zeros((Ks-3))
for max_d in range(3,ks):
    drugTree = DecisionTreeClassifier(criterion="entropy", max_depth = max_d)
    drugTree.fit(X_train,y_train)
    predTree = drugTree.predict(X_test)
    mean_ax[max_d-3] = metrics.accuracy_score(y_test, predTree)
mean_ax

array([0.64963504, 0.67153285, 0.70072993, 0.69343066, 0.7080292 ,
       0.73722628, 0.75912409, 0.7810219 , 0.78832117, 0.81021898,
       0.78832117, 0.78832117])

In [121]:
drugTree = DecisionTreeClassifier(criterion="entropy", max_depth = 12
                                 )
drugTree.fit(X_train,y_train)
predTree = drugTree.predict(X_test)

v3 = f1_score(y_test, predTree, average='weighted')
v4 = jaccard_similarity_score(y_test, predTree)

# Support Vector Machine

In [122]:
from sklearn import svm
clf = svm.SVC(kernel='rbf')
clf.fit(X_train, y_train) 
yhatsvm = clf.predict(X_test)

C:\Users\admin\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [123]:
v5 = f1_score(y_test, yhatsvm, average='weighted')
v6 = jaccard_similarity_score(y_test, yhatsvm)


# Logistic Regreession

In [124]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)
LR

C:\Users\admin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='liblinear',
          tol=0.0001, verbose=0, warm_start=False)

In [125]:
yhat = LR.predict(X_test)
yhat_prob = LR.predict_proba(X_test)
v7 = f1_score(y_test, yhat, average='weighted')
v8 = jaccard_similarity_score(y_test, yhat)
v9 = log_loss(y_test, yhat_prob)

C:\Users\admin\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


# Model Evaluation

In [126]:
# initialize list of lists 
data = [['KNN',v1,v2,np.nan],['Decision',v3,v4,np.nan],['SVM',v5,v6,np.nan],['LogisticRegression',v7,v8,v9]] 
  
# Create the pandas DataFrame 
df_final = pd.DataFrame(data, columns = ['Algorithm','Jaccard','F1-score','LogLoss']) 
  
# print dataframe. 
df_final 

Algorithm   Jaccard  F1-score   LogLoss
0                 KNN  0.761829  0.773723       NaN
1            Decision  0.794003  0.802920       NaN
2                 SVM  0.630811  0.678832       NaN
3  LogisticRegression  0.420313  0.547445  0.943566